---
- hosts: all
  become: yes
  vars:
    mysql_root_password: "@Balrajpasula5782"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache, MySQL, PHP, and required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php8.1
          - php8.1-mysql
          - libapache2-mod-php8.1
          - phpmyadmin
        state: present

    - name: Set MySQL root password
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password"
        value: "{{ mysql_root_password }}"
        vtype: "password"

    - name: Set MySQL root password again
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password_again"
        value: "{{ mysql_root_password }}"
        vtype: "password"

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Enable Apache mod_rewrite
      apache2_module:
        name: rewrite
        state: present

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Symlink phpmyadmin to Apache root
      file:
        src: /usr/share/phpmyadmin
        dest: /var/www/html/phpmyadmin
        state: link
        force: yes
